GET http://localhost:3001/todos

###



POST http://localhost:3001/todo/new
Content-Type: application/json 

{
    "text": "Order pizza",
    "deadLineTime": 60
}

###


DELETE http://localhost:3001/todo/delete/6563b5664395520575b241e1



###

PUT http://localhost:3001/todo/complete/6563b5934395520575b241e3
